### ISSUE TITLE
Animated VR Hands

### ISSUE THREAD

**Issue by Ashenoy64** [dscpesu/EscapeQuest#4]
#### Description
Implement animated VR hands that visually reflect the actions performed by the player using VR controllers through animations

#### Tasks

- [ ] **Make / Get a hand model:** Obtain or create a 3D hand model that will be used to represent the player's hands in the VR environment.

- [ ] **Rig the hands:** Set up a rigging system for the hand model. Rigging involves adding a skeleton and control points to the 3D model to enable realistic movement and animation.

- [ ] **Apply animations:** Develop or acquire animations that correspond to the various actions and movements the player can make with the VR controllers. These animations should be applied to the rigged hand model to make it responsive to player input.

- [ ] **Listen for the events:** Implement event listeners in your VR application to capture and interpret input from the VR controllers. These events should trigger the appropriate animations on the VR hands to match the player's actions.
